config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # get '/lists', to: 'lists#index'
  # get '/lists/new', to: 'lists#new', as: :new_list
  # post '/lists', to: 'lists#create'
  # get '/lists/:id', to: 'lists#show', as: :list

  root to: 'lists#index'

  resources :lists, only: [:index, :new, :create, :show] do
    resources :bookmarks, only: [:new, :create]
  end
    delete '/lists/:id', to: 'lists#destroy', as: :delete_list #put here as I want alias

    resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  validates :comment, length: { minimum: 6 }
  validates :movie, :list, presence: true
  validates :movie_id, uniqueness: { scope: :list_id, message: "Already bookmarked in this list" } # found on internet

  belongs_to :movie
  belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, uniqueness: true
  validates :name, presence: true

  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, uniqueness: true
  validates :title, presence: true
  validates :overview, presence: true

  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    # We need @bookmark in our `simple_form_for`
    @list = List.find(params[:list_id]) # not params[:id]
    @bookmark = Bookmark.new
  end

  def create
    # build the bookmark with content
    @bookmark = Bookmark.new(bookmark_params)
    # find the list
    @list = List.find(params[:list_id])
    # associate the bookmark with list instance (e.g: id 5)
    @bookmark.list = @list # or @bookmark.list_id = @list.id
    # save
    if @bookmark.save # if doesn't work, returns false
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity # HTTP 422 error
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    # @list = @bookmark.list # Retrieve the associated list
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to list_path(@list)
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class ="container mt-5">
  <h1>Add a new bookmark</h1>
  <div class="mt-5">
    <%= simple_form_for([@list, @bookmark]) do |f| %>
    <%= f.association :movie %>
    <%= f.input :comment %>
    <%= f.submit %>
    <% end %>
  </div>
  <br>
  <div> <%= link_to "Back", lists_path(@list), class: "btn-basic" %></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>

    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <div class="navbar-nav ms-auto">
        <%= link_to "Add a list", new_list_path(@list), class: "navbar-no-link-style" %>
      </div>
    </div>

    <%= yield %>

    <div class="footer">
      <div class="footer-copyright">
        This footer is made with <i class="fas fa-heart"></i> at Le Wagon
      </div>
    </div>

  </body>
</html>

app/views/lists/index.html.erb
<div class="banner-container">
  <div class="banner" style="background-image: url('<%= image_path('main_banner.jpg') %>');">
    <div class="container">
      <h1>My movie lists</h1>
      <p>Keep track of your favorite movies</p>
      <%= link_to "Add a list", new_list_path(@list), class: "btn-basic" %>
    </div>
  </div>
</div>

<div class="container mt-5">
  <% @lists.each do |list| %>
    <% if list.photo.attached? %>
      <div class="cards">
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.6)), url('<%= url_for(list.photo) %>')">
          <div class="card-contents">
            <%= link_to list.name, list_path(list), class: "card-name" %>
            <%= link_to "X", delete_list_path(list), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn-x"%>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/lists/new.html.erb
<div class ="container mt-5">
  <h1>Add a new list</h1>
    <%= simple_form_for(@list) do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.submit %>
  <% end %>
  <br>
  <%= link_to "Back", lists_path(@list), class: "btn-back" %>
</div>

app/views/lists/show.html.erb
<div class="banner-container">
  <div class="banner" style="background-image: url('<%= image_path('main_banner.jpg') %>');">
    <div class="container">
      <h1><%= @list.name %></h1>
    </div>
  </div>
</div>

<div class ="container mt-5">
  <div class="bookmark-info">
    <div class="bookmark-contents">
      <% @list.bookmarks.each do |bookmark| %>
        <h2><strong><%= bookmark.movie.title %></strong></h2>
        <ul>
          <li><%= bookmark.movie.poster_url %></li>
          <li><strong>description: </strong> <%= bookmark.movie.overview %></li>
          <li><strong>rating: </strong><%= bookmark.movie.rating %></li>
        </ul>
        <div>
          <p><strong>Comment:</strong></p>
          <p><%= bookmark.comment %></p>
        </div>
        <%= link_to "Delete", bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn-delete"%>
      <% end %>
        <div class="button-container">
          <%= link_to "Back", lists_path(@list), class: "btn-back" %>
          <%= link_to "Add a bookmark", new_list_bookmark_path(@list), class: "btn-basic" %>
        </div>
    </div>
  </div>
</div>